apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-bspprvkb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-bspprvkb:0ee0026f553f0634ecac9693fb82482e665d9c29@sha256:a8c84cbaae2dff1aa0cd8f922243df594f15e4868536edbfc0808cef6704ac4a
          name: container-image
